spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ashokit
    url: jdbc:mysql://127.0.0.1:3306/ihis
    username: ashokit
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true